-- ===============================
-- 👤 USERS TABLE
-- ===============================
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(200) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'learner' CHECK (role IN ('admin', 'mentor', 'learner')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- 🧭 LEARNING TRACKS
-- (e.g. Data Analytics, Web Dev)
-- ===============================
CREATE TABLE learning_tracks (
    track_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name VARCHAR2(150) NOT NULL,
    description CLOB,
    duration_weeks NUMBER,
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- 🎓 COURSES (Each Track has Courses)
-- ===============================
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id NUMBER NOT NULL,
    course_name VARCHAR2(150) NOT NULL,
    description CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id) ON DELETE CASCADE
);

-- ===============================
-- 📘 MODULES (Each Course has Modules)
-- ===============================
CREATE TABLE modules (
    module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    module_title VARCHAR2(200) NOT NULL,
    content CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);

-- ===============================
-- 📚 LESSONS (Each Module has Lessons)
-- ===============================
CREATE TABLE lessons (
    lesson_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id NUMBER NOT NULL,
    lesson_title VARCHAR2(200) NOT NULL,
    video_url VARCHAR2(500),
    content CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE
);

-- ===============================
-- 🧾 ENROLLMENTS (Learners in Tracks)
-- ===============================
CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    track_id NUMBER NOT NULL,
    enrollment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(50) DEFAULT 'enrolled' CHECK (status IN ('enrolled','completed','dropped')),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id) ON DELETE CASCADE,
    UNIQUE (user_id, track_id)
);

-- ===============================
-- 📈 PROGRESS TRACKING
-- (Mark lessons completed)
-- ===============================
CREATE TABLE lesson_progress (
    progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    lesson_id NUMBER NOT NULL,
    completed CHAR(1) DEFAULT 'N' CHECK (completed IN ('Y','N')),
    completed_at TIMESTAMP,
    FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
    FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    UNIQUE (enrollment_id, lesson_id)
);

-- ===============================
-- 🏅 CERTIFICATES
-- (Auto-issued after completion)
-- ===============================
CREATE TABLE certificates (
    certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    certificate_url VARCHAR2(500),
    FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
    UNIQUE (enrollment_id)
);
-- Add Users
INSERT INTO users (full_name, email, password_hash, role) VALUES 
('Admin User', 'admin@bootcamp.com', 'hashed_pw_admin', 'admin'),
('Jane Doe', 'jane@bootcamp.com', 'hashed_pw_learner', 'learner');

-- Add a Learning Track
INSERT INTO learning_tracks (track_name, description, duration_weeks)
VALUES ('Data Analytics Bootcamp', 'Learn data analytics tools, SQL, and visualization.', 12);

-- Add a Course under Track
INSERT INTO courses (track_id, course_name, description, order_no)
VALUES (1, 'Introduction to Data Analytics', 'Overview of analytics concepts', 1);

-- Add Module
INSERT INTO modules (course_id, module_title, content, order_no)
VALUES (1, 'Getting Started with Analytics', 'Welcome content', 1);

-- Add Lesson
INSERT INTO lessons (module_id, lesson_title, video_url, content)
VALUES (1, 'What is Data Analytics?', 'https://video.link/lesson1', 'Lesson overview');

-- Enroll User
INSERT INTO enrollments (user_id, track_id, status)
VALUES (2, 1, 'enrolled');

SELECT * FROM users;
INSERT INTO users (full_name, email, password_hash, role) VALUES 
('Susan Adams', 'sue@bootcamp.com', 'hashed_pw_learner', 'mentor');