-- ===============================
-- 👤 USERS TABLE
-- ===============================
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(200) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'learner' CHECK (role IN ('admin', 'mentor', 'learner')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- 🧭 LEARNING TRACKS
-- (e.g. Data Analytics, Web Dev)
-- ===============================
CREATE TABLE learning_tracks (
    track_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name VARCHAR2(150) NOT NULL,
    description CLOB,
    duration_weeks NUMBER,
    is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- 🎓 COURSES (Each Track has Courses)
-- ===============================
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id NUMBER NOT NULL,
    course_name VARCHAR2(150) NOT NULL,
    description CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id) ON DELETE CASCADE
);

-- ===============================
-- 📘 MODULES (Each Course has Modules)
-- ===============================
CREATE TABLE modules (
    module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    module_title VARCHAR2(200) NOT NULL,
    content CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);

-- ===============================
-- 📚 LESSONS (Each Module has Lessons)
-- ===============================
CREATE TABLE lessons (
    lesson_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id NUMBER NOT NULL,
    lesson_title VARCHAR2(200) NOT NULL,
    video_url VARCHAR2(500),
    content CLOB,
    order_no NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE
);

-- ===============================
-- 🧾 ENROLLMENTS (Learners in Tracks)
-- ===============================
CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    track_id NUMBER NOT NULL,
    enrollment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(50) DEFAULT 'enrolled' CHECK (status IN ('enrolled','completed','dropped')),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id) ON DELETE CASCADE,
    UNIQUE (user_id, track_id)
);

-- ===============================
-- 📈 PROGRESS TRACKING
-- (Mark lessons completed)
-- ===============================
CREATE TABLE lesson_progress (
    progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    lesson_id NUMBER NOT NULL,
    completed CHAR(1) DEFAULT 'N' CHECK (completed IN ('Y','N')),
    completed_at TIMESTAMP,
    FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
    FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    UNIQUE (enrollment_id, lesson_id)
);

-- ===============================
-- 🏅 CERTIFICATES
-- (Auto-issued after completion)
-- ===============================
CREATE TABLE certificates (
    certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    certificate_url VARCHAR2(500),
    FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
    UNIQUE (enrollment_id)
);

-- ===============================
-- 👤 EVENTS TABLE
-- ===============================
CREATE TABLE events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_topic VARCHAR2(150) NOT NULL,
    event_owner_userid VARCHAR2(200) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'learner' CHECK (role IN ('admin', 'mentor', 'learner')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(track_id) ON DELETE CASCADE
);


-- Add Users
INSERT INTO users (full_name, email, password_hash, role) VALUES 
('Admin User', 'admin@bootcamp.com', 'hashed_pw_admin', 'admin'),
('Jane Doe', 'jane@bootcamp.com', 'hashed_pw_learner', 'learner');

-- Add a Learning Track
INSERT INTO learning_tracks (track_name, description, duration_weeks)
VALUES ('Data Analytics Bootcamp', 'Learn data analytics tools, SQL, and visualization.', 12);

-- Add a Course under Track
INSERT INTO courses (track_id, course_name, description, order_no)
VALUES (1, 'Introduction to Data Analytics', 'Overview of analytics concepts', 1);

-- Add Module
INSERT INTO modules (course_id, module_title, content, order_no)
VALUES (1, 'Getting Started with Analytics', 'Welcome content', 1);

-- Add Lesson
INSERT INTO lessons (module_id, lesson_title, video_url, content)
VALUES (1, 'What is Data Analytics?', 'https://video.link/lesson1', 'Lesson overview');

-- Enroll User
INSERT INTO enrollments (user_id, track_id, status)
VALUES (2, 1, 'enrolled');

SELECT * FROM users;
INSERT INTO users (full_name, email, password_hash, role) VALUES 
('Susan Adams', 'sue@bootcamp.com', 'hashed_pw_learner', 'mentor');

ALTER TABLE USERS MODIFY PASSWORD_HASH NULL;

INSERT INTO users (full_name, email, password_hash, role) VALUES
('Alice Smith', 'alice@example.com', 'hashed_password_1', 'learner'),
('Bob Johnson', 'bob@example.com', 'hashed_password_2', 'learner'),
('Carol Lee', 'carol@example.com', 'hashed_password_3', 'mentor'),
('David Brown', 'david@example.com', 'hashed_password_4', 'admin');

INSERT INTO learning_tracks (track_name, description, duration_weeks) VALUES
('Data Analytics', 'Learn analytics, data visualization, and Python skills', 12),
('Web Development', 'Full stack web development with MERN stack', 16),
('Machine Learning', 'ML concepts, models, and deployment', 14);

INSERT INTO courses (track_id, course_name, description, order_no) VALUES
(1, 'Data Analytics Foundations', 'Intro to data analytics', 1),
(1, 'Python for Data Analytics', 'Learn Python for data manipulation', 2),
(2, 'Frontend Development', 'HTML, CSS, JavaScript basics', 1),
(2, 'Backend Development', 'Node.js, Express, MongoDB', 2),
(3, 'Intro to Machine Learning', 'ML fundamentals', 1);


INSERT INTO modules (course_id, module_title, content, order_no) VALUES
(26, 'Introduction to Data', 'Overview of datasets and analytics', 1),
(26, 'Data Cleaning', 'Techniques for cleaning data', 2),
(27, 'Python Basics', 'Variables, loops, functions', 1),
(27, 'Pandas & NumPy', 'Data analysis libraries', 2),
(28, 'HTML & CSS', 'Building webpage structure and style', 1),
(29, 'Node.js & Express', 'Server-side development', 1),
(29, 'Supervised Learning', 'Regression and classification', 1);

INSERT INTO lessons (module_id, lesson_title, video_url, content, order_no) VALUES
(1, 'What is Data Analytics?', 'https://example.com/video1', 'Introduction content', 1),
(2, 'Cleaning Datasets', 'https://example.com/video2', 'Step-by-step guide', 1),
(3, 'Python Syntax Basics', 'https://example.com/video3', 'Learn Python basics', 1),
(4, 'Using Pandas', 'https://example.com/video4', 'Dataframes and Series', 1),
(5, 'HTML Structure', 'https://example.com/video5', 'HTML tags and layout', 1),
(6, 'Express Routes', 'https://example.com/video6', 'Server routing', 1),
(7, 'Regression Models', 'https://example.com/video7', 'Linear regression', 1);

INSERT INTO enrollments (user_id, track_id, status) VALUES
(1, 1, 'enrolled'), -- Alice enrolled in Data Analytics
(2, 2, 'enrolled'), -- Bob enrolled in Web Development
(1, 2, 'enrolled'); -- Alice also enrolled in Web Development

INSERT INTO lesson_progress (enrollment_id, lesson_id, completed, completed_at) VALUES
(1, 1, 'Y', CURRENT_TIMESTAMP), -- Alice completed first lesson
(1, 2, 'N', NULL),               -- Alice not yet completed
(2, 5, 'Y', CURRENT_TIMESTAMP); -- Bob completed HTML lesson

INSERT INTO certificates (enrollment_id, certificate_url) VALUES
(1, 'https://example.com/certificates/alice-data-analytics.pdf');

CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing project ID
    name VARCHAR2(255) NOT NULL,  -- Project name
    description CLOB,  -- Detailed description of the project
    status VARCHAR2(50) DEFAULT 'Planned' CHECK (status IN ('Planned', 'Ongoing', 'Completed')),  -- Project status
    start_date DATE,  -- Date when the project started
    end_date DATE,  -- Date when the project ended (if applicable)
    technology_stack CLOB,  -- List of technologies used (e.g., React, Node.js)
    github_link VARCHAR2(255),  -- Link to the project's GitHub repo (if applicable)
    live_link VARCHAR2(255),  -- Link to the live project (if applicable)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp of when the project was created
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp of when the project was last updated
    track_id NUMBER,  -- Foreign Key to the Learning Tracks table
    user_id NUMBER,  -- Foreign Key to the Users table (linked to a specific learner)
    CONSTRAINT fk_track FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id),  -- Foreign Key to Learning Tracks
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id)  -- Foreign Key to Users table (student/learner)
);

CREATE OR REPLACE TRIGGER update_project_timestamp
BEFORE UPDATE ON projects
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


INSERT INTO projects (name, description, status, start_date, end_date, technology_stack, github_link, live_link, track_id, user_id)
VALUES
('Website Redesign for E-commerce', 
 'A complete redesign of an e-commerce platform focusing on enhancing user experience and performance.', 
 'Ongoing', 
 TO_DATE('2025-01-10', 'YYYY-MM-DD'), 
 NULL, 
 'HTML, CSS, JavaScript, React, Node.js, MongoDB', 
 'https://github.com/username/ecommerce-redesign', 
 'https://ecommerce-redesign.com', 
 28,  -- Assuming track_id 1 corresponds to Web Development track
 66);  -- Assuming user_id 101 corresponds to the user responsible for the project

INSERT INTO projects (name, description, status, start_date, end_date, technology_stack, github_link, live_link, track_id, user_id)
VALUES
('Data Analysis for Retail Sales', 
 'An analytics project focused on retail sales data, providing insights for improving inventory and marketing strategies.',
 'Completed', 
 TO_DATE('2025-02-15', 'YYYY-MM-DD'), 
 TO_DATE('2025-03-01', 'YYYY-MM-DD'), 
 'Python, Pandas, NumPy, Matplotlib, SQL', 
 'https://github.com/username/retail-sales-analysis', 
 'https://retail-sales-analysis.com', 
 27,  -- Assuming track_id 2 corresponds to Data Science track
 66);  -- Assuming user_id 102 corresponds to the user responsible for the project

INSERT INTO projects (name, description, status, start_date, end_date, technology_stack, github_link, live_link, track_id, user_id)
VALUES
('Machine Learning Model for Customer Segmentation', 
 'Developed a machine learning model to segment customers based on purchasing behavior and demographic data.',
 'Ongoing', 
 TO_DATE('2025-03-01', 'YYYY-MM-DD'), 
 NULL, 
 'Python, Scikit-learn, K-means Clustering, Pandas', 
 'https://github.com/username/customer-segmentation', 
 'https://customer-segmentation.com', 
 29,  -- Assuming track_id 3 corresponds to Machine Learning track
 66);  -- Assuming user_id 103 corresponds to the user responsible for the project

INSERT INTO projects (name, description, status, start_date, end_date, technology_stack, github_link, live_link, track_id, user_id)
VALUES
('Mobile App for Personal Finance', 
 'A mobile app that helps users track their personal finances, create budgets, and set financial goals.',
 'Planned', 
 TO_DATE('2025-04-01', 'YYYY-MM-DD'), 
 NULL, 
 'Flutter, Dart, Firebase', 
 'https://github.com/username/personal-finance-app', 
 'https://personal-finance-app.com', 
 28,  -- Assuming track_id 4 corresponds to Mobile App Development track
 66);  -- Assuming user_id 104 corresponds to the user responsible for the project





SELECT c.track_id, lt.track_name,c.course_name, c.description,
             m.module_id, m.module_title
      FROM enrollments e
      LEFT JOIN courses c ON e.track_id = c.track_id
      LEFT JOIN modules m ON c.course_id = m.course_id
      LEFT JOIN learning_tracks lt ON e.track_id = lt.track_id
    WHERE e.user_id = 66;

ALTER TABLE users ADD avatar VARCHAR2(512);

ALTER TABLE courses ADD (new_varchar_col VARCHAR2(32767));

UPDATE courses
SET new_varchar_col = DBMS_LOB.SUBSTR(description, 32767, 1);

ALTER TABLE courses DROP COLUMN description;
ALTER TABLE projects ADD (description VARCHAR2(4000));

ALTER TABLE courses RENAME COLUMN new_varchar_col TO description;

CREATE TABLE mentor_learner (
    user_id NUMBER NOT NULL,
    mentor_id NUMBER NOT NULL,
    track_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, mentor_id, track_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (mentor_id) REFERENCES users(user_id),
    FOREIGN KEY (track_id) REFERENCES learning_tracks(track_id)
);

CREATE TABLE assignments (
    assignment_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    course_id       NUMBER NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    due_date        DATE,
    description     VARCHAR2(4000),
    course_file           VARCHAR2(500),
    CONSTRAINT fk_assignments_course
      FOREIGN KEY (course_id) REFERENCES courses(course_id)
      ON DELETE CASCADE
);

CREATE TABLE course_materials (
    cm_id         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    course_id  NUMBER NOT NULL,
    title      VARCHAR2(200) NOT NULL,
    file_path  VARCHAR2(500) NOT NULL,
    CONSTRAINT fk_course_materials_course
      FOREIGN KEY (course_id) REFERENCES courses(course_id)
      ON DELETE CASCADE
);